<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Title>gestionaleCasere</Title>
    <Authors>Riccardo_Buso</Authors>
    <Product>gestionale_casere</Product>
    <AssemblyName>agRiB</AssemblyName>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <ApplicationIcon>icona_gestionale_cantina_102916.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- Mantieni solo il riferimento NuGet per MySql.Data -->
    <PackageReference Include="Aspose.Cells" Version="24.10.0" />
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Microsoft.Data.Analysis" Version="0.21.1" />
    <PackageReference Include="MySql.Data" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Rimosso il riferimento diretto a MySql.Data per evitare conflitti -->
    <!-- Rimosso il riferimento a MySQLInstaller, non necessario per la compilazione -->
  </ItemGroup>

</Project>