<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
  </PropertyGroup>

  <!-- AGGIUNGI QUESTA SEZIONE COMPLETA -->
  <ItemGroup>
    <!-- Copia cartella manuale -->
    <None Include="manuale\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    
    <!-- Copia file paswd.txt -->
    <None Include="paswd.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!-- I tuoi PackageReference esistenti -->
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
  </ItemGroup>

</Project>